spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/idmapp
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-here-make-it-long-and-secure}
  expiration: 86400000  # 24 hours in milliseconds

logging:
  level:
    com.example.usermanagement: DEBUG

server:
  port: 8081

auth0:
  domain: dev-df4lud4n6zz4i5tg.us.auth0.com
  client-id: ${AUTH0_CLIENT_ID}
  client-secret: ${AUTH0_CLIENT_SECRET}
  audience: /api/v1/
